name: CI_ES3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  test:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Runs a set of commands using the runners shell
    - name: Install clang
      run: | 
        apt install clang
        npm i
        npm run es3_test
  
